# Generated by Django 4.1.6 on 2023-02-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(default='2000-12-12'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Customer', 'Customer'), ('Loan_Representative', 'Loan_Representative'), ('Operational_Head', 'Operational_Head'), ('Loan_Sanction_Officer', 'Loan_Sanction_Officer'), ('Admin', 'Admin')], default='Customer', max_length=50),
        ),
    ]
