# Generated by Django 4.1.6 on 2023-02-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_verification', '0002_alter_document_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Inprocess', 'Inprocess')], default=0, max_length=250),
        ),
    ]
